# Generated by Django 6.0.3 on 2026-04-05 15:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PRODUCE", "Produce / Vegetables / Fruit"),
                            ("MEAT", "Meat / Poultry / Seafood"),
                            ("DAIRY", "Dairy / Fridge"),
                            ("PANTRY", "Pantry / Dry Goods"),
                            ("SPICES", "Spices / Condiments"),
                            ("BREAD", "Bakery / Bread"),
                            ("DRINKS", "Drinks"),
                            ("FROZEN", "Frozen"),
                            ("NON_FOOD", "Non-Food / General"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                (
                    "base_unit",
                    models.CharField(help_text="e.g. grams, pieces, ml", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Camp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("default_people_count", models.PositiveIntegerField(default=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneralCampItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PRODUCE", "Produce / Vegetables / Fruit"),
                            ("MEAT", "Meat / Poultry / Seafood"),
                            ("DAIRY", "Dairy / Fridge"),
                            ("PANTRY", "Pantry / Dry Goods"),
                            ("SPICES", "Spices / Condiments"),
                            ("BREAD", "Bakery / Bread"),
                            ("DRINKS", "Drinks"),
                            ("FROZEN", "Frozen"),
                            ("NON_FOOD", "Non-Food / General"),
                            ("OTHER", "Other"),
                        ],
                        default="NON_FOOD",
                        max_length=50,
                    ),
                ),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_items",
                        to="meals.camp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of dietary tags like Vegan, Gluten-Free",
                    ),
                ),
                (
                    "default_portions",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many people this recipe serves as written",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampMeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Breakfast"),
                            ("MORNING_SNACK", "Morning Snack (Z'nüni)"),
                            ("LUNCH", "Lunch"),
                            ("AFTERNOON_SNACK", "Afternoon Snack (Z'vieri)"),
                            ("DINNER", "Dinner"),
                            ("DESSERT", "Dessert"),
                            ("NIGHT_SNACK", "Night Snack"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "override_people_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Overrides camp's default count",
                        null=True,
                    ),
                ),
                (
                    "leftovers_noted",
                    models.TextField(
                        blank=True, help_text="Note what was left over after meal"
                    ),
                ),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="meals.camp",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="meals.recipe"
                    ),
                ),
            ],
            options={
                "ordering": ["date", "meal_type"],
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="meals.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="meals.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shared_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_list",
                        to="meals.camp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_name", models.CharField(blank=True, max_length=255)),
                ("amount", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("is_checked", models.BooleanField(default=False)),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meals.ingredient",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="meals.shoppinglist",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "ingredient__name", "custom_name"],
            },
        ),
        migrations.CreateModel(
            name="IngredientUnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(
                        help_text="e.g. tbsp, tsp, piece, kilogram", max_length=50
                    ),
                ),
                (
                    "multiplier",
                    models.FloatField(help_text="Multiply by this to get base_unit"),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="meals.ingredient",
                    ),
                ),
            ],
            options={
                "unique_together": {("ingredient", "unit_name")},
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_bought", models.FloatField(default=0)),
                ("quantity_used", models.FloatField(default=0)),
                ("unit", models.CharField(max_length=50)),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="meals.camp",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meals.ingredient",
                    ),
                ),
            ],
            options={
                "unique_together": {("camp", "ingredient")},
            },
        ),
    ]
