# Generated by Django 6.0.3 on 2026-04-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="camp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_lists",
                to="meals.camp",
            ),
        ),
    ]
