# Generated by Django 6.0.3 on 2026-04-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0002_alter_shoppinglist_camp"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredientunitconversion",
            name="needs_review",
            field=models.BooleanField(
                default=False,
                help_text="Set to true if automatically captured from a recipe and needs admin conversion factor",
            ),
        ),
    ]
