# Generated by Django 6.0.3 on 2026-04-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_shoppinglistitem_source_meals_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_importing',
            field=models.BooleanField(default=False, help_text='True if AI is currently parsing this recipe in the background'),
        ),
    ]
