# Generated by Django 6.0.3 on 2026-04-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0009_camp_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="campmeal",
            name="is_done",
            field=models.BooleanField(
                default=False, help_text="Mark if this meal has been cooked/consumed"
            ),
        ),
    ]
