# Generated by Django 6.0.3 on 2026-04-05 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0010_campmeal_is_done"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="collaboration_camps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
