# Generated by Django 6.0.3 on 2026-04-06 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0011_camp_collaborators"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="collaboration_recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
