# Generated by Django 6.0.3 on 2026-04-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0012_recipe_collaborators"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="name_de",
            field=models.CharField(
                db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="name_fr",
            field=models.CharField(
                db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="instructions_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name_de",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
