// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  ContentApiGetTextsData,
  ContentApiGetTextsResponses,
  CoreApiAccountData,
  CoreApiAccountResponses,
  CoreApiChangePasswordViewData,
  CoreApiChangePasswordViewErrors,
  CoreApiChangePasswordViewResponses,
  CoreApiGetCurrentUserStatusData,
  CoreApiGetCurrentUserStatusResponses,
  CoreApiGetMessagesData,
  CoreApiGetMessagesResponses,
  CoreApiLoginViewData,
  CoreApiLoginViewErrors,
  CoreApiLoginViewResponses,
  CoreApiLogoutViewData,
  CoreApiLogoutViewResponses,
  CoreApiPasswordResetConfirmData,
  CoreApiPasswordResetConfirmResponses,
  CoreApiPasswordResetRequestData,
  CoreApiPasswordResetRequestResponses,
  CoreApiSetLanguageData,
  CoreApiSetLanguageResponses,
  CoreApiUpdateProfileData,
  CoreApiUpdateProfileResponses,
  MealsApiCampsCreateCampData,
  MealsApiCampsCreateCampGeneralItemData,
  MealsApiCampsCreateCampGeneralItemResponses,
  MealsApiCampsCreateCampResponses,
  MealsApiCampsDeleteCampData,
  MealsApiCampsDeleteCampGeneralItemData,
  MealsApiCampsDeleteCampGeneralItemResponses,
  MealsApiCampsDeleteCampResponses,
  MealsApiCampsGetCampData,
  MealsApiCampsGetCampResponses,
  MealsApiCampsInviteCollaboratorData,
  MealsApiCampsInviteCollaboratorResponses,
  MealsApiCampsListCampGeneralItemsData,
  MealsApiCampsListCampGeneralItemsResponses,
  MealsApiCampsListCampsData,
  MealsApiCampsListCampsResponses,
  MealsApiCampsRemoveCollaboratorData,
  MealsApiCampsRemoveCollaboratorResponses,
  MealsApiCampsUpdateCampData,
  MealsApiCampsUpdateCampResponses,
  MealsApiIngredientsCreateIngredientData,
  MealsApiIngredientsCreateIngredientResponses,
  MealsApiIngredientsListIngredientsData,
  MealsApiIngredientsListIngredientsResponses,
  MealsApiIngredientsListTagsData,
  MealsApiIngredientsListTagsResponses,
  MealsApiIngredientsListUnitsData,
  MealsApiIngredientsListUnitsResponses,
  MealsApiInventoryExportInventoryExcelData,
  MealsApiInventoryExportInventoryExcelResponses,
  MealsApiInventoryGetInventoryStatusData,
  MealsApiInventoryGetInventoryStatusResponses,
  MealsApiMealsCreateCampMealData,
  MealsApiMealsCreateCampMealResponses,
  MealsApiMealsDeleteCampMealData,
  MealsApiMealsDeleteCampMealResponses,
  MealsApiMealsListCampMealsData,
  MealsApiMealsListCampMealsResponses,
  MealsApiMealsToggleCampMealDoneData,
  MealsApiMealsToggleCampMealDoneResponses,
  MealsApiMealsUpdateCampMealData,
  MealsApiMealsUpdateCampMealResponses,
  MealsApiRecipesAddRecipeIngredientData,
  MealsApiRecipesAddRecipeIngredientResponses,
  MealsApiRecipesCreateRecipeData,
  MealsApiRecipesCreateRecipeResponses,
  MealsApiRecipesDeleteRecipeIngredientData,
  MealsApiRecipesDeleteRecipeIngredientResponses,
  MealsApiRecipesGetRecipeData,
  MealsApiRecipesGetRecipeResponses,
  MealsApiRecipesImportRecipeData,
  MealsApiRecipesImportRecipeResponses,
  MealsApiRecipesInviteRecipeCollaboratorData,
  MealsApiRecipesInviteRecipeCollaboratorResponses,
  MealsApiRecipesListPreferencesData,
  MealsApiRecipesListPreferencesResponses,
  MealsApiRecipesListRecipeIngredientsData,
  MealsApiRecipesListRecipeIngredientsResponses,
  MealsApiRecipesListRecipesData,
  MealsApiRecipesListRecipesResponses,
  MealsApiRecipesRemoveRecipeCollaboratorData,
  MealsApiRecipesRemoveRecipeCollaboratorResponses,
  MealsApiRecipesUpdateRecipeData,
  MealsApiRecipesUpdateRecipeIngredientData,
  MealsApiRecipesUpdateRecipeIngredientResponses,
  MealsApiRecipesUpdateRecipeResponses,
  MealsApiShoppingAddManualShoppingItemData,
  MealsApiShoppingAddManualShoppingItemResponses,
  MealsApiShoppingDeleteShoppingListData,
  MealsApiShoppingDeleteShoppingListResponses,
  MealsApiShoppingExportSharedShoppingListData,
  MealsApiShoppingExportSharedShoppingListResponses,
  MealsApiShoppingExportShoppingListData,
  MealsApiShoppingExportShoppingListResponses,
  MealsApiShoppingGenerateShoppingListData,
  MealsApiShoppingGenerateShoppingListResponses,
  MealsApiShoppingGetSharedShoppingListData,
  MealsApiShoppingGetSharedShoppingListResponses,
  MealsApiShoppingGetShoppingListData,
  MealsApiShoppingGetShoppingListResponses,
  MealsApiShoppingListCampShoppingListsData,
  MealsApiShoppingListCampShoppingListsResponses,
  MealsApiShoppingMoveGeneralItemsToShoppingListData,
  MealsApiShoppingMoveGeneralItemsToShoppingListResponses,
  MealsApiShoppingSharedShoppingListEventsData,
  MealsApiShoppingSharedShoppingListEventsResponses,
  MealsApiShoppingToggleSharedShoppingItemData,
  MealsApiShoppingToggleSharedShoppingItemResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login View
 */
export const coreApiLoginView = <ThrowOnError extends boolean = false>(
  options: Options<CoreApiLoginViewData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CoreApiLoginViewResponses,
    CoreApiLoginViewErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Logout View
 */
export const coreApiLogoutView = <ThrowOnError extends boolean = false>(
  options?: Options<CoreApiLogoutViewData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    CoreApiLogoutViewResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/auth/logout",
    ...options,
  });

/**
 * Change Password View
 */
export const coreApiChangePasswordView = <ThrowOnError extends boolean = false>(
  options: Options<CoreApiChangePasswordViewData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CoreApiChangePasswordViewResponses,
    CoreApiChangePasswordViewErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/auth/set-password",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Account
 */
export const coreApiAccount = <ThrowOnError extends boolean = false>(
  options?: Options<CoreApiAccountData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CoreApiAccountResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/auth/account", ...options });

/**
 * Update Profile
 */
export const coreApiUpdateProfile = <ThrowOnError extends boolean = false>(
  options: Options<CoreApiUpdateProfileData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CoreApiUpdateProfileResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/auth/profile",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Password Reset Request
 */
export const coreApiPasswordResetRequest = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CoreApiPasswordResetRequestData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CoreApiPasswordResetRequestResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/api/auth/password-reset-request",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Password Reset Confirm
 */
export const coreApiPasswordResetConfirm = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CoreApiPasswordResetConfirmData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CoreApiPasswordResetConfirmResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/api/auth/password-reset-confirm",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Set Language
 */
export const coreApiSetLanguage = <ThrowOnError extends boolean = false>(
  options: Options<CoreApiSetLanguageData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    CoreApiSetLanguageResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/set-language/", ...options });

/**
 * Get Current User Status
 */
export const coreApiGetCurrentUserStatus = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CoreApiGetCurrentUserStatusData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CoreApiGetCurrentUserStatusResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/meals/auth/me", ...options });

/**
 * Get Messages
 */
export const coreApiGetMessages = <ThrowOnError extends boolean = false>(
  options?: Options<CoreApiGetMessagesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    CoreApiGetMessagesResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/messages/", ...options });

/**
 * List Camps
 */
export const mealsApiCampsListCamps = <ThrowOnError extends boolean = false>(
  options?: Options<MealsApiCampsListCampsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    MealsApiCampsListCampsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps",
    ...options,
  });

/**
 * Create Camp
 */
export const mealsApiCampsCreateCamp = <ThrowOnError extends boolean = false>(
  options: Options<MealsApiCampsCreateCampData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MealsApiCampsCreateCampResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Camp
 */
export const mealsApiCampsDeleteCamp = <ThrowOnError extends boolean = false>(
  options: Options<MealsApiCampsDeleteCampData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    MealsApiCampsDeleteCampResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}",
    ...options,
  });

/**
 * Get Camp
 */
export const mealsApiCampsGetCamp = <ThrowOnError extends boolean = false>(
  options: Options<MealsApiCampsGetCampData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiCampsGetCampResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}",
    ...options,
  });

/**
 * Update Camp
 */
export const mealsApiCampsUpdateCamp = <ThrowOnError extends boolean = false>(
  options: Options<MealsApiCampsUpdateCampData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    MealsApiCampsUpdateCampResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Invite Collaborator
 */
export const mealsApiCampsInviteCollaborator = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiCampsInviteCollaboratorData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MealsApiCampsInviteCollaboratorResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/collaborators",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove Collaborator
 */
export const mealsApiCampsRemoveCollaborator = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiCampsRemoveCollaboratorData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    MealsApiCampsRemoveCollaboratorResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/collaborators/{username}",
    ...options,
  });

/**
 * List Camp General Items
 */
export const mealsApiCampsListCampGeneralItems = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiCampsListCampGeneralItemsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiCampsListCampGeneralItemsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/general-items",
    ...options,
  });

/**
 * Create Camp General Item
 */
export const mealsApiCampsCreateCampGeneralItem = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiCampsCreateCampGeneralItemData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MealsApiCampsCreateCampGeneralItemResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/general-items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Camp General Item
 */
export const mealsApiCampsDeleteCampGeneralItem = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiCampsDeleteCampGeneralItemData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    MealsApiCampsDeleteCampGeneralItemResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/general-items/{item_id}",
    ...options,
  });

/**
 * List Recipes
 */
export const mealsApiRecipesListRecipes = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MealsApiRecipesListRecipesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    MealsApiRecipesListRecipesResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/recipes",
    ...options,
  });

/**
 * Create Recipe
 */
export const mealsApiRecipesCreateRecipe = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiRecipesCreateRecipeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MealsApiRecipesCreateRecipeResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/recipes",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Import Recipe
 */
export const mealsApiRecipesImportRecipe = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiRecipesImportRecipeData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MealsApiRecipesImportRecipeResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/recipes/import",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Recipe
 */
export const mealsApiRecipesGetRecipe = <ThrowOnError extends boolean = false>(
  options: Options<MealsApiRecipesGetRecipeData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiRecipesGetRecipeResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/recipes/{recipe_id}",
    ...options,
  });

/**
 * Update Recipe
 */
export const mealsApiRecipesUpdateRecipe = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiRecipesUpdateRecipeData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    MealsApiRecipesUpdateRecipeResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/recipes/{recipe_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Recipe Ingredients
 */
export const mealsApiRecipesListRecipeIngredients = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiRecipesListRecipeIngredientsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiRecipesListRecipeIngredientsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/recipes/{recipe_id}/ingredients",
    ...options,
  });

/**
 * Add Recipe Ingredient
 */
export const mealsApiRecipesAddRecipeIngredient = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiRecipesAddRecipeIngredientData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MealsApiRecipesAddRecipeIngredientResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/recipes/{recipe_id}/ingredients",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Recipe Ingredient
 */
export const mealsApiRecipesDeleteRecipeIngredient = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiRecipesDeleteRecipeIngredientData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    MealsApiRecipesDeleteRecipeIngredientResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/recipes/{recipe_id}/ingredients/{ingredient_id}",
    ...options,
  });

/**
 * Update Recipe Ingredient
 */
export const mealsApiRecipesUpdateRecipeIngredient = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiRecipesUpdateRecipeIngredientData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    MealsApiRecipesUpdateRecipeIngredientResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/recipes/{recipe_id}/ingredients/{ingredient_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Invite Recipe Collaborator
 */
export const mealsApiRecipesInviteRecipeCollaborator = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiRecipesInviteRecipeCollaboratorData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MealsApiRecipesInviteRecipeCollaboratorResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/recipes/{recipe_id}/collaborators",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove Recipe Collaborator
 */
export const mealsApiRecipesRemoveRecipeCollaborator = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiRecipesRemoveRecipeCollaboratorData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    MealsApiRecipesRemoveRecipeCollaboratorResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/recipes/{recipe_id}/collaborators/{username}",
    ...options,
  });

/**
 * List Preferences
 */
export const mealsApiRecipesListPreferences = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MealsApiRecipesListPreferencesData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    MealsApiRecipesListPreferencesResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/preferences",
    ...options,
  });

/**
 * List Ingredients
 */
export const mealsApiIngredientsListIngredients = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MealsApiIngredientsListIngredientsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    MealsApiIngredientsListIngredientsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/ingredients",
    ...options,
  });

/**
 * Create Ingredient
 */
export const mealsApiIngredientsCreateIngredient = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiIngredientsCreateIngredientData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MealsApiIngredientsCreateIngredientResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/ingredients",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Units
 */
export const mealsApiIngredientsListUnits = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MealsApiIngredientsListUnitsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    MealsApiIngredientsListUnitsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/units",
    ...options,
  });

/**
 * List Tags
 */
export const mealsApiIngredientsListTags = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<MealsApiIngredientsListTagsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    MealsApiIngredientsListTagsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/tags",
    ...options,
  });

/**
 * List Camp Meals
 */
export const mealsApiMealsListCampMeals = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiMealsListCampMealsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiMealsListCampMealsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/meals",
    ...options,
  });

/**
 * Create Camp Meal
 */
export const mealsApiMealsCreateCampMeal = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiMealsCreateCampMealData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MealsApiMealsCreateCampMealResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/meals",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Camp Meal
 */
export const mealsApiMealsDeleteCampMeal = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiMealsDeleteCampMealData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    MealsApiMealsDeleteCampMealResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/meals/{meal_id}",
    ...options,
  });

/**
 * Update Camp Meal
 */
export const mealsApiMealsUpdateCampMeal = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiMealsUpdateCampMealData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    MealsApiMealsUpdateCampMealResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/meals/{meal_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Toggle Camp Meal Done
 */
export const mealsApiMealsToggleCampMealDone = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiMealsToggleCampMealDoneData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    MealsApiMealsToggleCampMealDoneResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/meals/{meal_id}/toggle-done",
    ...options,
  });

/**
 * Add Manual Shopping Item
 */
export const mealsApiShoppingAddManualShoppingItem = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiShoppingAddManualShoppingItemData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MealsApiShoppingAddManualShoppingItemResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/shopping-lists/add-manual-item",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Generate Shopping List
 */
export const mealsApiShoppingGenerateShoppingList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiShoppingGenerateShoppingListData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MealsApiShoppingGenerateShoppingListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/shopping-list/generate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Move General Items To Shopping List
 */
export const mealsApiShoppingMoveGeneralItemsToShoppingList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    MealsApiShoppingMoveGeneralItemsToShoppingListData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    MealsApiShoppingMoveGeneralItemsToShoppingListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/shopping-lists/{list_id}/move-general-items",
    ...options,
  });

/**
 * Delete Shopping List
 */
export const mealsApiShoppingDeleteShoppingList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiShoppingDeleteShoppingListData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    MealsApiShoppingDeleteShoppingListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/shopping-lists/{list_id}",
    ...options,
  });

/**
 * Get Shopping List
 */
export const mealsApiShoppingGetShoppingList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiShoppingGetShoppingListData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiShoppingGetShoppingListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/shopping-lists/{list_id}",
    ...options,
  });

/**
 * Export Shopping List
 */
export const mealsApiShoppingExportShoppingList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiShoppingExportShoppingListData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiShoppingExportShoppingListResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/shopping-lists/{list_id}/export",
    ...options,
  });

/**
 * List Camp Shopping Lists
 */
export const mealsApiShoppingListCampShoppingLists = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiShoppingListCampShoppingListsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiShoppingListCampShoppingListsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/shopping-lists",
    ...options,
  });

/**
 * Get Shared Shopping List
 */
export const mealsApiShoppingGetSharedShoppingList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiShoppingGetSharedShoppingListData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiShoppingGetSharedShoppingListResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/meals/shared/shopping-lists/{token}", ...options });

/**
 * Export Shared Shopping List
 */
export const mealsApiShoppingExportSharedShoppingList = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiShoppingExportSharedShoppingListData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiShoppingExportSharedShoppingListResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/meals/shared/shopping-lists/{token}/export", ...options });

/**
 * Shared Shopping List Events
 */
export const mealsApiShoppingSharedShoppingListEvents = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiShoppingSharedShoppingListEventsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiShoppingSharedShoppingListEventsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/meals/shared/shopping-lists/{token}/events", ...options });

/**
 * Toggle Shared Shopping Item
 */
export const mealsApiShoppingToggleSharedShoppingItem = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiShoppingToggleSharedShoppingItemData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    MealsApiShoppingToggleSharedShoppingItemResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/meals/shared/shopping-lists/{token}/items/{item_id}/toggle",
    ...options,
  });

/**
 * Get Inventory Status
 */
export const mealsApiInventoryGetInventoryStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiInventoryGetInventoryStatusData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiInventoryGetInventoryStatusResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/inventory-status",
    ...options,
  });

/**
 * Export Inventory Excel
 */
export const mealsApiInventoryExportInventoryExcel = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MealsApiInventoryExportInventoryExcelData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    MealsApiInventoryExportInventoryExcelResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "sessionid",
        type: "apiKey",
      },
    ],
    url: "/api/meals/camps/{camp_id}/inventory-status/export",
    ...options,
  });

/**
 * Get Texts
 *
 * Return all UI texts as a flat key→value dict for the given language.
 */
export const contentApiGetTexts = <ThrowOnError extends boolean = false>(
  options?: Options<ContentApiGetTextsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ContentApiGetTextsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/content/texts/", ...options });
