// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
  /**
   * Success
   */
  success: boolean;
  /**
   * Error
   */
  error?: string | null;
};

/**
 * AccountResponse
 */
export type AccountResponse = {
  /**
   * Username
   */
  username: string | null;
  /**
   * Is Staff
   */
  is_staff?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Verified
   */
  verified?: boolean | null;
  /**
   * Otp
   */
  otp?: boolean | null;
  /**
   * Is Trusted
   */
  is_trusted?: boolean | null;
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
};

/**
 * CurrentUserStatusSchema
 */
export type CurrentUserStatusSchema = {
  /**
   * Is Logged In
   */
  is_logged_in: boolean;
  /**
   * Username
   */
  username: string | null;
};

/**
 * CampSchema
 */
export type CampSchema = {
  /**
   * Owner Username
   */
  owner_username?: string | null;
  /**
   * Collaborators
   */
  collaborators?: Array<string>;
  /**
   * Id
   */
  id?: string | null;
  /**
   * Name
   */
  name: string;
  /**
   * Default People Count
   */
  default_people_count?: number;
  /**
   * Start Date
   */
  start_date: string;
  /**
   * End Date
   */
  end_date: string;
  /**
   * Notes
   *
   * General notes for the camp (e.g., special events, allergies summary)
   */
  notes?: string | null;
};

/**
 * CampCreateSchema
 */
export type CampCreateSchema = {
  /**
   * Name
   */
  name: string;
  /**
   * Default People Count
   */
  default_people_count?: number;
  /**
   * Start Date
   */
  start_date: string;
  /**
   * End Date
   */
  end_date: string;
};

/**
 * CampUpdateSchema
 */
export type CampUpdateSchema = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Default People Count
   */
  default_people_count?: number | null;
  /**
   * Notes
   */
  notes?: string | null;
};

/**
 * CollaboratorInviteSchema
 */
export type CollaboratorInviteSchema = {
  /**
   * Username
   */
  username: string;
};

/**
 * GeneralCampItemSchema
 */
export type GeneralCampItemSchema = {
  /**
   * ID
   */
  id?: number | null;
  /**
   * Camp
   */
  camp: string;
  /**
   * Name
   */
  name: string;
  /**
   * Amount
   */
  amount: string;
  /**
   * Category
   */
  category?: string;
};

/**
 * GeneralCampItemCreateSchema
 */
export type GeneralCampItemCreateSchema = {
  /**
   * Name
   */
  name: string;
  /**
   * Amount
   */
  amount: string;
  /**
   * Category
   */
  category?: string;
};

/**
 * Input
 */
export type Input = {
  /**
   * Page
   */
  page?: number;
  /**
   * Page Size
   */
  page_size?: number | null;
};

/**
 * DietaryPreferenceSchema
 */
export type DietaryPreferenceSchema = {
  /**
   * ID
   */
  id?: number | null;
  /**
   * Name
   */
  name: string;
};

/**
 * PagedRecipeSchema
 */
export type PagedRecipeSchema = {
  /**
   * Items
   */
  items: Array<RecipeSchema>;
  /**
   * Count
   */
  count: number;
};

/**
 * RecipeSchema
 */
export type RecipeSchema = {
  /**
   * Preferences
   */
  preferences?: Array<DietaryPreferenceSchema>;
  /**
   * Tags
   */
  tags?: Array<string>;
  /**
   * Owner Username
   */
  owner_username?: string | null;
  /**
   * Collaborators
   */
  collaborators?: Array<string>;
  /**
   * Id
   */
  id?: string | null;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Instructions
   */
  instructions?: string | null;
  /**
   * Default Portions
   *
   * How many people this recipe serves as written
   */
  default_portions?: number;
  /**
   * Is Importing
   *
   * True if AI is currently parsing this recipe in the background
   */
  is_importing?: boolean;
};

/**
 * RecipeCreateSchema
 */
export type RecipeCreateSchema = {
  /**
   * Preference Ids
   */
  preference_ids?: Array<number>;
  /**
   * Tags
   */
  tags?: Array<string>;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Instructions
   */
  instructions?: string | null;
  /**
   * Default Portions
   *
   * How many people this recipe serves as written
   */
  default_portions?: number;
};

/**
 * RecipeImportRequestSchema
 */
export type RecipeImportRequestSchema = {
  /**
   * Raw Text
   */
  raw_text: string;
};

/**
 * RecipeUpdateSchema
 */
export type RecipeUpdateSchema = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Instructions
   */
  instructions?: string | null;
  /**
   * Default Portions
   */
  default_portions?: number | null;
  /**
   * Preference Ids
   */
  preference_ids?: Array<number> | null;
  /**
   * Tags
   */
  tags?: Array<string>;
};

/**
 * IngredientSchema
 */
export type IngredientSchema = {
  /**
   * Id
   */
  id?: string | null;
  /**
   * Name
   */
  name: string;
  /**
   * Category
   */
  category?: string;
  /**
   * Base Unit
   *
   * e.g. grams, pieces, ml
   */
  base_unit: string;
};

/**
 * RecipeIngredientSchema
 */
export type RecipeIngredientSchema = {
  ingredient: IngredientSchema;
  /**
   * ID
   */
  id?: number | null;
  /**
   * Amount
   */
  amount: number;
  /**
   * Unit
   */
  unit: string;
};

/**
 * RecipeIngredientCreateOrMapSchema
 */
export type RecipeIngredientCreateOrMapSchema = {
  /**
   * Ingredient Name
   */
  ingredient_name: string;
  /**
   * Amount
   */
  amount: number;
  /**
   * Unit
   */
  unit: string;
};

/**
 * RecipeIngredientUpdateSchema
 */
export type RecipeIngredientUpdateSchema = {
  /**
   * Amount
   */
  amount: number;
  /**
   * Unit
   */
  unit: string;
};

/**
 * IngredientCreateSchema
 */
export type IngredientCreateSchema = {
  /**
   * Name
   */
  name: string;
  /**
   * Category
   */
  category?: string;
  /**
   * Base Unit
   *
   * e.g. grams, pieces, ml
   */
  base_unit: string;
};

/**
 * CampMealSchema
 */
export type CampMealSchema = {
  serves_preference?: DietaryPreferenceSchema | null;
  /**
   * Recipe Name
   */
  recipe_name?: string;
  /**
   * Recipe Default Portions
   */
  recipe_default_portions?: number;
  /**
   * Id
   */
  id?: string | null;
  /**
   * Camp
   */
  camp: string;
  /**
   * Recipe
   */
  recipe: string;
  /**
   * Meal Type
   */
  meal_type: string;
  /**
   * Date
   */
  date: string;
  /**
   * Override People Count
   *
   * Overrides camp's default count
   */
  override_people_count?: number | null;
  /**
   * Leftovers Noted
   *
   * Note what was left over after meal
   */
  leftovers_noted?: string | null;
  /**
   * Is Done
   *
   * Mark if this meal has been cooked/consumed
   */
  is_done?: boolean;
};

/**
 * CampMealCreateSchema
 */
export type CampMealCreateSchema = {
  /**
   * Recipe Id
   */
  recipe_id: string;
  /**
   * Meal Type
   */
  meal_type: string;
  /**
   * Date
   */
  date: string;
  /**
   * Override People Count
   */
  override_people_count?: number;
  /**
   * Serves Preference Id
   */
  serves_preference_id?: number;
};

/**
 * CampMealUpdateSchema
 */
export type CampMealUpdateSchema = {
  /**
   * Override People Count
   */
  override_people_count?: number | null;
  /**
   * Serves Preference Id
   */
  serves_preference_id?: number | null;
};

/**
 * ShoppingListItemSchema
 */
export type ShoppingListItemSchema = {
  ingredient?: IngredientSchema | null;
  /**
   * Source Meals Text
   */
  source_meals_text?: Array<string>;
  /**
   * ID
   */
  id?: number | null;
  /**
   * Shopping List
   */
  shopping_list: string;
  /**
   * Custom Name
   */
  custom_name?: string | null;
  /**
   * Amount
   */
  amount: number;
  /**
   * Unit
   */
  unit: string;
  /**
   * Category
   */
  category: string;
  /**
   * Is Checked
   */
  is_checked?: boolean;
};

/**
 * ShoppingListManualItemSchema
 */
export type ShoppingListManualItemSchema = {
  /**
   * Ingredient Id
   */
  ingredient_id: string;
  /**
   * Amount
   */
  amount: number;
  /**
   * Unit
   */
  unit: string;
};

/**
 * ShoppingListSchema
 */
export type ShoppingListSchema = {
  /**
   * Id
   */
  id: string;
  /**
   * Camp Id
   */
  camp_id: string;
  /**
   * Shared Token
   */
  shared_token: string;
  /**
   * Items
   */
  items: Array<ShoppingListItemSchema>;
};

/**
 * ShoppingListGenerateRequestSchema
 */
export type ShoppingListGenerateRequestSchema = {
  /**
   * Meal Ids
   */
  meal_ids: Array<string>;
};

/**
 * ShoppingListOverviewSchema
 */
export type ShoppingListOverviewSchema = {
  /**
   * Id
   */
  id: string;
  /**
   * Camp Id
   */
  camp_id: string;
  /**
   * Shared Token
   */
  shared_token: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Included Meals
   */
  included_meals: Array<string>;
};

/**
 * InventoryStatusSchema
 */
export type InventoryStatusSchema = {
  /**
   * Ingredient Id
   */
  ingredient_id: string;
  /**
   * Ingredient Name
   */
  ingredient_name: string;
  /**
   * Category
   */
  category: string;
  /**
   * Unit
   */
  unit: string;
  /**
   * Quantity Bought
   */
  quantity_bought: number;
  /**
   * Quantity Required
   */
  quantity_required: number;
  /**
   * Balance
   */
  balance: number;
};

export type CoreApiLoginViewData = {
  /**
   * FormParams
   */
  body: {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
  };
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type CoreApiLoginViewErrors = {
  /**
   * Unauthorized
   */
  401: LoginResponse;
};

export type CoreApiLoginViewError =
  CoreApiLoginViewErrors[keyof CoreApiLoginViewErrors];

export type CoreApiLoginViewResponses = {
  /**
   * OK
   */
  200: LoginResponse;
};

export type CoreApiLoginViewResponse =
  CoreApiLoginViewResponses[keyof CoreApiLoginViewResponses];

export type CoreApiLogoutViewData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/logout";
};

export type CoreApiLogoutViewResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type CoreApiChangePasswordViewData = {
  /**
   * FormParams
   */
  body: {
    /**
     * Old Password
     */
    old_password: string;
    /**
     * New Password
     */
    new_password: string;
  };
  path?: never;
  query?: never;
  url: "/api/auth/set-password";
};

export type CoreApiChangePasswordViewErrors = {
  /**
   * Unauthorized
   */
  401: LoginResponse;
};

export type CoreApiChangePasswordViewError =
  CoreApiChangePasswordViewErrors[keyof CoreApiChangePasswordViewErrors];

export type CoreApiChangePasswordViewResponses = {
  /**
   * OK
   */
  200: LoginResponse;
};

export type CoreApiChangePasswordViewResponse =
  CoreApiChangePasswordViewResponses[keyof CoreApiChangePasswordViewResponses];

export type CoreApiAccountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/account";
};

export type CoreApiAccountResponses = {
  /**
   * OK
   */
  200: AccountResponse;
};

export type CoreApiAccountResponse =
  CoreApiAccountResponses[keyof CoreApiAccountResponses];

export type CoreApiUpdateProfileData = {
  /**
   * FormParams
   */
  body: {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
  };
  path?: never;
  query?: never;
  url: "/api/auth/profile";
};

export type CoreApiUpdateProfileResponses = {
  /**
   * OK
   */
  200: AccountResponse;
};

export type CoreApiUpdateProfileResponse =
  CoreApiUpdateProfileResponses[keyof CoreApiUpdateProfileResponses];

export type CoreApiPasswordResetRequestData = {
  /**
   * FormParams
   */
  body: {
    /**
     * Email
     */
    email: string;
  };
  path?: never;
  query?: never;
  url: "/api/auth/password-reset-request";
};

export type CoreApiPasswordResetRequestResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type CoreApiPasswordResetConfirmData = {
  /**
   * FormParams
   */
  body: {
    /**
     * Uid
     */
    uid: string;
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
  };
  path?: never;
  query?: never;
  url: "/api/auth/password-reset-confirm";
};

export type CoreApiPasswordResetConfirmResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type CoreApiSetLanguageData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Language
     */
    language: string;
  };
  url: "/api/set-language/";
};

export type CoreApiSetLanguageResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type CoreApiGetCurrentUserStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/meals/auth/me";
};

export type CoreApiGetCurrentUserStatusResponses = {
  /**
   * OK
   */
  200: CurrentUserStatusSchema;
};

export type CoreApiGetCurrentUserStatusResponse =
  CoreApiGetCurrentUserStatusResponses[keyof CoreApiGetCurrentUserStatusResponses];

export type CoreApiGetMessagesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/messages/";
};

export type CoreApiGetMessagesResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<[string, string]>;
};

export type CoreApiGetMessagesResponse =
  CoreApiGetMessagesResponses[keyof CoreApiGetMessagesResponses];

export type MealsApiCampsListCampsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/meals/camps";
};

export type MealsApiCampsListCampsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<CampSchema>;
};

export type MealsApiCampsListCampsResponse =
  MealsApiCampsListCampsResponses[keyof MealsApiCampsListCampsResponses];

export type MealsApiCampsCreateCampData = {
  body: CampCreateSchema;
  path?: never;
  query?: never;
  url: "/api/meals/camps";
};

export type MealsApiCampsCreateCampResponses = {
  /**
   * OK
   */
  200: CampSchema;
};

export type MealsApiCampsCreateCampResponse =
  MealsApiCampsCreateCampResponses[keyof MealsApiCampsCreateCampResponses];

export type MealsApiCampsDeleteCampData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}";
};

export type MealsApiCampsDeleteCampResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type MealsApiCampsGetCampData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}";
};

export type MealsApiCampsGetCampResponses = {
  /**
   * OK
   */
  200: CampSchema;
};

export type MealsApiCampsGetCampResponse =
  MealsApiCampsGetCampResponses[keyof MealsApiCampsGetCampResponses];

export type MealsApiCampsUpdateCampData = {
  body: CampUpdateSchema;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}";
};

export type MealsApiCampsUpdateCampResponses = {
  /**
   * OK
   */
  200: CampSchema;
};

export type MealsApiCampsUpdateCampResponse =
  MealsApiCampsUpdateCampResponses[keyof MealsApiCampsUpdateCampResponses];

export type MealsApiCampsInviteCollaboratorData = {
  body: CollaboratorInviteSchema;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/collaborators";
};

export type MealsApiCampsInviteCollaboratorResponses = {
  /**
   * OK
   */
  200: CampSchema;
};

export type MealsApiCampsInviteCollaboratorResponse =
  MealsApiCampsInviteCollaboratorResponses[keyof MealsApiCampsInviteCollaboratorResponses];

export type MealsApiCampsRemoveCollaboratorData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
    /**
     * Username
     */
    username: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/collaborators/{username}";
};

export type MealsApiCampsRemoveCollaboratorResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type MealsApiCampsListCampGeneralItemsData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/general-items";
};

export type MealsApiCampsListCampGeneralItemsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<GeneralCampItemSchema>;
};

export type MealsApiCampsListCampGeneralItemsResponse =
  MealsApiCampsListCampGeneralItemsResponses[keyof MealsApiCampsListCampGeneralItemsResponses];

export type MealsApiCampsCreateCampGeneralItemData = {
  body: GeneralCampItemCreateSchema;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/general-items";
};

export type MealsApiCampsCreateCampGeneralItemResponses = {
  /**
   * OK
   */
  200: GeneralCampItemSchema;
};

export type MealsApiCampsCreateCampGeneralItemResponse =
  MealsApiCampsCreateCampGeneralItemResponses[keyof MealsApiCampsCreateCampGeneralItemResponses];

export type MealsApiCampsDeleteCampGeneralItemData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/general-items/{item_id}";
};

export type MealsApiCampsDeleteCampGeneralItemResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type MealsApiRecipesListRecipesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Q
     */
    q?: string | null;
    /**
     * Tags
     */
    tags?: string | null;
    /**
     * Preference Id
     */
    preference_id?: number | null;
    /**
     * Ids
     */
    ids?: string | null;
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number | null;
  };
  url: "/api/meals/recipes";
};

export type MealsApiRecipesListRecipesResponses = {
  /**
   * OK
   */
  200: PagedRecipeSchema;
};

export type MealsApiRecipesListRecipesResponse =
  MealsApiRecipesListRecipesResponses[keyof MealsApiRecipesListRecipesResponses];

export type MealsApiRecipesCreateRecipeData = {
  body: RecipeCreateSchema;
  path?: never;
  query?: never;
  url: "/api/meals/recipes";
};

export type MealsApiRecipesCreateRecipeResponses = {
  /**
   * OK
   */
  200: RecipeSchema;
};

export type MealsApiRecipesCreateRecipeResponse =
  MealsApiRecipesCreateRecipeResponses[keyof MealsApiRecipesCreateRecipeResponses];

export type MealsApiRecipesImportRecipeData = {
  body: RecipeImportRequestSchema;
  path?: never;
  query?: never;
  url: "/api/meals/recipes/import";
};

export type MealsApiRecipesImportRecipeResponses = {
  /**
   * OK
   */
  200: RecipeSchema;
};

export type MealsApiRecipesImportRecipeResponse =
  MealsApiRecipesImportRecipeResponses[keyof MealsApiRecipesImportRecipeResponses];

export type MealsApiRecipesGetRecipeData = {
  body?: never;
  path: {
    /**
     * Recipe Id
     */
    recipe_id: string;
  };
  query?: never;
  url: "/api/meals/recipes/{recipe_id}";
};

export type MealsApiRecipesGetRecipeResponses = {
  /**
   * OK
   */
  200: RecipeSchema;
};

export type MealsApiRecipesGetRecipeResponse =
  MealsApiRecipesGetRecipeResponses[keyof MealsApiRecipesGetRecipeResponses];

export type MealsApiRecipesUpdateRecipeData = {
  body: RecipeUpdateSchema;
  path: {
    /**
     * Recipe Id
     */
    recipe_id: string;
  };
  query?: never;
  url: "/api/meals/recipes/{recipe_id}";
};

export type MealsApiRecipesUpdateRecipeResponses = {
  /**
   * OK
   */
  200: RecipeSchema;
};

export type MealsApiRecipesUpdateRecipeResponse =
  MealsApiRecipesUpdateRecipeResponses[keyof MealsApiRecipesUpdateRecipeResponses];

export type MealsApiRecipesListRecipeIngredientsData = {
  body?: never;
  path: {
    /**
     * Recipe Id
     */
    recipe_id: string;
  };
  query?: never;
  url: "/api/meals/recipes/{recipe_id}/ingredients";
};

export type MealsApiRecipesListRecipeIngredientsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<RecipeIngredientSchema>;
};

export type MealsApiRecipesListRecipeIngredientsResponse =
  MealsApiRecipesListRecipeIngredientsResponses[keyof MealsApiRecipesListRecipeIngredientsResponses];

export type MealsApiRecipesAddRecipeIngredientData = {
  body: RecipeIngredientCreateOrMapSchema;
  path: {
    /**
     * Recipe Id
     */
    recipe_id: string;
  };
  query?: never;
  url: "/api/meals/recipes/{recipe_id}/ingredients";
};

export type MealsApiRecipesAddRecipeIngredientResponses = {
  /**
   * OK
   */
  200: RecipeIngredientSchema;
};

export type MealsApiRecipesAddRecipeIngredientResponse =
  MealsApiRecipesAddRecipeIngredientResponses[keyof MealsApiRecipesAddRecipeIngredientResponses];

export type MealsApiRecipesDeleteRecipeIngredientData = {
  body?: never;
  path: {
    /**
     * Recipe Id
     */
    recipe_id: string;
    /**
     * Ingredient Id
     */
    ingredient_id: string;
  };
  query?: never;
  url: "/api/meals/recipes/{recipe_id}/ingredients/{ingredient_id}";
};

export type MealsApiRecipesDeleteRecipeIngredientResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type MealsApiRecipesUpdateRecipeIngredientData = {
  body: RecipeIngredientUpdateSchema;
  path: {
    /**
     * Recipe Id
     */
    recipe_id: string;
    /**
     * Ingredient Id
     */
    ingredient_id: string;
  };
  query?: never;
  url: "/api/meals/recipes/{recipe_id}/ingredients/{ingredient_id}";
};

export type MealsApiRecipesUpdateRecipeIngredientResponses = {
  /**
   * OK
   */
  200: RecipeIngredientSchema;
};

export type MealsApiRecipesUpdateRecipeIngredientResponse =
  MealsApiRecipesUpdateRecipeIngredientResponses[keyof MealsApiRecipesUpdateRecipeIngredientResponses];

export type MealsApiRecipesInviteRecipeCollaboratorData = {
  body: CollaboratorInviteSchema;
  path: {
    /**
     * Recipe Id
     */
    recipe_id: string;
  };
  query?: never;
  url: "/api/meals/recipes/{recipe_id}/collaborators";
};

export type MealsApiRecipesInviteRecipeCollaboratorResponses = {
  /**
   * OK
   */
  200: RecipeSchema;
};

export type MealsApiRecipesInviteRecipeCollaboratorResponse =
  MealsApiRecipesInviteRecipeCollaboratorResponses[keyof MealsApiRecipesInviteRecipeCollaboratorResponses];

export type MealsApiRecipesRemoveRecipeCollaboratorData = {
  body?: never;
  path: {
    /**
     * Recipe Id
     */
    recipe_id: string;
    /**
     * Username
     */
    username: string;
  };
  query?: never;
  url: "/api/meals/recipes/{recipe_id}/collaborators/{username}";
};

export type MealsApiRecipesRemoveRecipeCollaboratorResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type MealsApiRecipesListPreferencesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/meals/preferences";
};

export type MealsApiRecipesListPreferencesResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<DietaryPreferenceSchema>;
};

export type MealsApiRecipesListPreferencesResponse =
  MealsApiRecipesListPreferencesResponses[keyof MealsApiRecipesListPreferencesResponses];

export type MealsApiIngredientsListIngredientsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Q
     */
    q?: string | null;
  };
  url: "/api/meals/ingredients";
};

export type MealsApiIngredientsListIngredientsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<IngredientSchema>;
};

export type MealsApiIngredientsListIngredientsResponse =
  MealsApiIngredientsListIngredientsResponses[keyof MealsApiIngredientsListIngredientsResponses];

export type MealsApiIngredientsCreateIngredientData = {
  body: IngredientCreateSchema;
  path?: never;
  query?: never;
  url: "/api/meals/ingredients";
};

export type MealsApiIngredientsCreateIngredientResponses = {
  /**
   * OK
   */
  200: IngredientSchema;
};

export type MealsApiIngredientsCreateIngredientResponse =
  MealsApiIngredientsCreateIngredientResponses[keyof MealsApiIngredientsCreateIngredientResponses];

export type MealsApiIngredientsListUnitsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/meals/units";
};

export type MealsApiIngredientsListUnitsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<string>;
};

export type MealsApiIngredientsListUnitsResponse =
  MealsApiIngredientsListUnitsResponses[keyof MealsApiIngredientsListUnitsResponses];

export type MealsApiIngredientsListTagsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/meals/tags";
};

export type MealsApiIngredientsListTagsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<string>;
};

export type MealsApiIngredientsListTagsResponse =
  MealsApiIngredientsListTagsResponses[keyof MealsApiIngredientsListTagsResponses];

export type MealsApiMealsListCampMealsData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/meals";
};

export type MealsApiMealsListCampMealsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<CampMealSchema>;
};

export type MealsApiMealsListCampMealsResponse =
  MealsApiMealsListCampMealsResponses[keyof MealsApiMealsListCampMealsResponses];

export type MealsApiMealsCreateCampMealData = {
  body: CampMealCreateSchema;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/meals";
};

export type MealsApiMealsCreateCampMealResponses = {
  /**
   * OK
   */
  200: CampMealSchema;
};

export type MealsApiMealsCreateCampMealResponse =
  MealsApiMealsCreateCampMealResponses[keyof MealsApiMealsCreateCampMealResponses];

export type MealsApiMealsDeleteCampMealData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
    /**
     * Meal Id
     */
    meal_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/meals/{meal_id}";
};

export type MealsApiMealsDeleteCampMealResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type MealsApiMealsUpdateCampMealData = {
  body: CampMealUpdateSchema;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
    /**
     * Meal Id
     */
    meal_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/meals/{meal_id}";
};

export type MealsApiMealsUpdateCampMealResponses = {
  /**
   * OK
   */
  200: CampMealSchema;
};

export type MealsApiMealsUpdateCampMealResponse =
  MealsApiMealsUpdateCampMealResponses[keyof MealsApiMealsUpdateCampMealResponses];

export type MealsApiMealsToggleCampMealDoneData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
    /**
     * Meal Id
     */
    meal_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/meals/{meal_id}/toggle-done";
};

export type MealsApiMealsToggleCampMealDoneResponses = {
  /**
   * OK
   */
  200: CampMealSchema;
};

export type MealsApiMealsToggleCampMealDoneResponse =
  MealsApiMealsToggleCampMealDoneResponses[keyof MealsApiMealsToggleCampMealDoneResponses];

export type MealsApiShoppingAddManualShoppingItemData = {
  body: ShoppingListManualItemSchema;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/shopping-lists/add-manual-item";
};

export type MealsApiShoppingAddManualShoppingItemResponses = {
  /**
   * OK
   */
  200: ShoppingListItemSchema;
};

export type MealsApiShoppingAddManualShoppingItemResponse =
  MealsApiShoppingAddManualShoppingItemResponses[keyof MealsApiShoppingAddManualShoppingItemResponses];

export type MealsApiShoppingGenerateShoppingListData = {
  body: ShoppingListGenerateRequestSchema;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/shopping-list/generate";
};

export type MealsApiShoppingGenerateShoppingListResponses = {
  /**
   * OK
   */
  200: ShoppingListSchema;
};

export type MealsApiShoppingGenerateShoppingListResponse =
  MealsApiShoppingGenerateShoppingListResponses[keyof MealsApiShoppingGenerateShoppingListResponses];

export type MealsApiShoppingMoveGeneralItemsToShoppingListData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
    /**
     * List Id
     */
    list_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/shopping-lists/{list_id}/move-general-items";
};

export type MealsApiShoppingMoveGeneralItemsToShoppingListResponses = {
  /**
   * OK
   */
  200: ShoppingListSchema;
};

export type MealsApiShoppingMoveGeneralItemsToShoppingListResponse =
  MealsApiShoppingMoveGeneralItemsToShoppingListResponses[keyof MealsApiShoppingMoveGeneralItemsToShoppingListResponses];

export type MealsApiShoppingDeleteShoppingListData = {
  body?: never;
  path: {
    /**
     * List Id
     */
    list_id: string;
  };
  query?: never;
  url: "/api/meals/shopping-lists/{list_id}";
};

export type MealsApiShoppingDeleteShoppingListResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type MealsApiShoppingGetShoppingListData = {
  body?: never;
  path: {
    /**
     * List Id
     */
    list_id: string;
  };
  query?: never;
  url: "/api/meals/shopping-lists/{list_id}";
};

export type MealsApiShoppingGetShoppingListResponses = {
  /**
   * OK
   */
  200: ShoppingListSchema;
};

export type MealsApiShoppingGetShoppingListResponse =
  MealsApiShoppingGetShoppingListResponses[keyof MealsApiShoppingGetShoppingListResponses];

export type MealsApiShoppingExportShoppingListData = {
  body?: never;
  path: {
    /**
     * List Id
     */
    list_id: string;
  };
  query?: never;
  url: "/api/meals/shopping-lists/{list_id}/export";
};

export type MealsApiShoppingExportShoppingListResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type MealsApiShoppingListCampShoppingListsData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/shopping-lists";
};

export type MealsApiShoppingListCampShoppingListsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<ShoppingListOverviewSchema>;
};

export type MealsApiShoppingListCampShoppingListsResponse =
  MealsApiShoppingListCampShoppingListsResponses[keyof MealsApiShoppingListCampShoppingListsResponses];

export type MealsApiShoppingGetSharedShoppingListData = {
  body?: never;
  path: {
    /**
     * Token
     */
    token: string;
  };
  query?: never;
  url: "/api/meals/shared/shopping-lists/{token}";
};

export type MealsApiShoppingGetSharedShoppingListResponses = {
  /**
   * OK
   */
  200: ShoppingListSchema;
};

export type MealsApiShoppingGetSharedShoppingListResponse =
  MealsApiShoppingGetSharedShoppingListResponses[keyof MealsApiShoppingGetSharedShoppingListResponses];

export type MealsApiShoppingExportSharedShoppingListData = {
  body?: never;
  path: {
    /**
     * Token
     */
    token: string;
  };
  query?: never;
  url: "/api/meals/shared/shopping-lists/{token}/export";
};

export type MealsApiShoppingExportSharedShoppingListResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type MealsApiShoppingSharedShoppingListEventsData = {
  body?: never;
  path: {
    /**
     * Token
     */
    token: string;
  };
  query?: never;
  url: "/api/meals/shared/shopping-lists/{token}/events";
};

export type MealsApiShoppingSharedShoppingListEventsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type MealsApiShoppingToggleSharedShoppingItemData = {
  body?: never;
  path: {
    /**
     * Token
     */
    token: string;
    /**
     * Item Id
     */
    item_id: string;
  };
  query?: never;
  url: "/api/meals/shared/shopping-lists/{token}/items/{item_id}/toggle";
};

export type MealsApiShoppingToggleSharedShoppingItemResponses = {
  /**
   * OK
   */
  200: ShoppingListItemSchema;
};

export type MealsApiShoppingToggleSharedShoppingItemResponse =
  MealsApiShoppingToggleSharedShoppingItemResponses[keyof MealsApiShoppingToggleSharedShoppingItemResponses];

export type MealsApiInventoryGetInventoryStatusData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/inventory-status";
};

export type MealsApiInventoryGetInventoryStatusResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<InventoryStatusSchema>;
};

export type MealsApiInventoryGetInventoryStatusResponse =
  MealsApiInventoryGetInventoryStatusResponses[keyof MealsApiInventoryGetInventoryStatusResponses];

export type MealsApiInventoryExportInventoryExcelData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/meals/camps/{camp_id}/inventory-status/export";
};

export type MealsApiInventoryExportInventoryExcelResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ContentApiGetTextsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Lang
     */
    lang?: string;
  };
  url: "/api/content/texts/";
};

export type ContentApiGetTextsResponses = {
  /**
   * OK
   */
  200: unknown;
};
