// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * AccountResponse
 */
export type AccountResponse = {
    /**
     * Username
     */
    username: string | null;
    /**
     * Is Staff
     */
    is_staff?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Verified
     */
    verified?: boolean | null;
    /**
     * Otp
     */
    otp?: boolean | null;
    /**
     * Is Trusted
     */
    is_trusted?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * CampSchema
 */
export type CampSchema = {
    /**
     * Owner Username
     */
    owner_username?: string | null;
    /**
     * Collaborators
     */
    collaborators?: Array<string>;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Default People Count
     */
    default_people_count?: number;
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
    /**
     * Notes
     *
     * General notes for the camp (e.g., special events, allergies summary)
     */
    notes?: string | null;
};

/**
 * CampCreateSchema
 */
export type CampCreateSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Default People Count
     */
    default_people_count?: number;
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
};

/**
 * CampUpdateSchema
 */
export type CampUpdateSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Default People Count
     */
    default_people_count?: number | null;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * CollaboratorInviteSchema
 */
export type CollaboratorInviteSchema = {
    /**
     * Username
     */
    username: string;
};

/**
 * CurrentUserStatusSchema
 */
export type CurrentUserStatusSchema = {
    /**
     * Is Logged In
     */
    is_logged_in: boolean;
    /**
     * Username
     */
    username: string | null;
};

/**
 * CampMealSchema
 */
export type CampMealSchema = {
    serves_preference?: DietaryPreferenceSchema | null;
    /**
     * Recipe Name
     */
    recipe_name?: string;
    /**
     * Recipe Default Portions
     */
    recipe_default_portions?: number;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Camp
     */
    camp: string;
    /**
     * Recipe
     */
    recipe: string;
    /**
     * Meal Type
     */
    meal_type: string;
    /**
     * Date
     */
    date: string;
    /**
     * Override People Count
     *
     * Overrides camp's default count
     */
    override_people_count?: number | null;
    /**
     * Leftovers Noted
     *
     * Note what was left over after meal
     */
    leftovers_noted?: string | null;
    /**
     * Is Done
     *
     * Mark if this meal has been cooked/consumed
     */
    is_done?: boolean;
};

/**
 * DietaryPreferenceSchema
 */
export type DietaryPreferenceSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
};

/**
 * InventoryStatusSchema
 */
export type InventoryStatusSchema = {
    /**
     * Ingredient Id
     */
    ingredient_id: string;
    /**
     * Ingredient Name
     */
    ingredient_name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Quantity Bought
     */
    quantity_bought: number;
    /**
     * Quantity Required
     */
    quantity_required: number;
    /**
     * Balance
     */
    balance: number;
};

/**
 * IngredientSchema
 */
export type IngredientSchema = {
    /**
     * Id
     */
    id?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category?: string;
    /**
     * Base Unit
     *
     * e.g. grams, pieces, ml
     */
    base_unit: string;
};

/**
 * IngredientCreateSchema
 */
export type IngredientCreateSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category?: string;
    /**
     * Base Unit
     *
     * e.g. grams, pieces, ml
     */
    base_unit: string;
};

/**
 * RecipePaginatedSchema
 */
export type RecipePaginatedSchema = {
    /**
     * Items
     */
    items: Array<RecipeSchema>;
    /**
     * Count
     */
    count: number;
};

/**
 * RecipeSchema
 */
export type RecipeSchema = {
    /**
     * Preferences
     */
    preferences?: Array<DietaryPreferenceSchema>;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Owner Username
     */
    owner_username?: string | null;
    /**
     * Collaborators
     */
    collaborators?: Array<string>;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Default Portions
     *
     * How many people this recipe serves as written
     */
    default_portions?: number;
    /**
     * Is Importing
     *
     * True if AI is currently parsing this recipe in the background
     */
    is_importing?: boolean;
};

/**
 * RecipeCreateSchema
 */
export type RecipeCreateSchema = {
    /**
     * Preference Ids
     */
    preference_ids?: Array<number>;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Default Portions
     *
     * How many people this recipe serves as written
     */
    default_portions?: number;
};

/**
 * RecipeImportRequestSchema
 */
export type RecipeImportRequestSchema = {
    /**
     * Raw Text
     */
    raw_text: string;
};

/**
 * RecipeUpdateSchema
 */
export type RecipeUpdateSchema = {
    /**
     * Name
     */
    name?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Instructions
     */
    instructions?: string;
    /**
     * Default Portions
     */
    default_portions?: number;
    /**
     * Preference Ids
     */
    preference_ids?: Array<number>;
    /**
     * Tags
     */
    tags?: Array<string>;
};

/**
 * RecipeIngredientSchema
 */
export type RecipeIngredientSchema = {
    ingredient: IngredientSchema;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Amount
     */
    amount: number;
    /**
     * Unit
     */
    unit: string;
};

/**
 * RecipeIngredientCreateOrMapSchema
 */
export type RecipeIngredientCreateOrMapSchema = {
    /**
     * Ingredient Name
     */
    ingredient_name: string;
    /**
     * Amount
     */
    amount: number;
    /**
     * Unit
     */
    unit: string;
};

/**
 * RecipeIngredientUpdateSchema
 */
export type RecipeIngredientUpdateSchema = {
    /**
     * Amount
     */
    amount: number;
    /**
     * Unit
     */
    unit: string;
};

/**
 * CampMealCreateSchema
 */
export type CampMealCreateSchema = {
    /**
     * Recipe Id
     */
    recipe_id: string;
    /**
     * Meal Type
     */
    meal_type: string;
    /**
     * Date
     */
    date: string;
    /**
     * Override People Count
     */
    override_people_count?: number;
    /**
     * Serves Preference Id
     */
    serves_preference_id?: number;
};

/**
 * CampMealUpdateSchema
 */
export type CampMealUpdateSchema = {
    /**
     * Override People Count
     */
    override_people_count?: number | null;
    /**
     * Serves Preference Id
     */
    serves_preference_id?: number | null;
};

/**
 * GeneralCampItemSchema
 */
export type GeneralCampItemSchema = {
    /**
     * ID
     */
    id?: number | null;
    /**
     * Camp
     */
    camp: string;
    /**
     * Name
     */
    name: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Category
     */
    category?: string;
};

/**
 * GeneralCampItemCreateSchema
 */
export type GeneralCampItemCreateSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Category
     */
    category?: string;
};

/**
 * ShoppingListItemSchema
 */
export type ShoppingListItemSchema = {
    ingredient?: IngredientSchema | null;
    /**
     * Source Meals Text
     */
    source_meals_text?: Array<string>;
    /**
     * ID
     */
    id?: number | null;
    /**
     * Shopping List
     */
    shopping_list: string;
    /**
     * Custom Name
     */
    custom_name?: string | null;
    /**
     * Amount
     */
    amount: number;
    /**
     * Unit
     */
    unit: string;
    /**
     * Category
     */
    category: string;
    /**
     * Is Checked
     */
    is_checked?: boolean;
};

/**
 * ShoppingListManualItemSchema
 */
export type ShoppingListManualItemSchema = {
    /**
     * Ingredient Id
     */
    ingredient_id: string;
    /**
     * Amount
     */
    amount: number;
    /**
     * Unit
     */
    unit: string;
};

/**
 * ShoppingListSchema
 */
export type ShoppingListSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Camp Id
     */
    camp_id: string;
    /**
     * Shared Token
     */
    shared_token: string;
    /**
     * Items
     */
    items: Array<ShoppingListItemSchema>;
};

/**
 * ShoppingListGenerateRequestSchema
 */
export type ShoppingListGenerateRequestSchema = {
    /**
     * Meal Ids
     */
    meal_ids: Array<string>;
};

/**
 * ShoppingListOverviewSchema
 */
export type ShoppingListOverviewSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Camp Id
     */
    camp_id: string;
    /**
     * Shared Token
     */
    shared_token: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Included Meals
     */
    included_meals: Array<string>;
};

export type CoreApiLoginViewData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Username
         */
        username: string;
        /**
         * Password
         */
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type CoreApiLoginViewErrors = {
    /**
     * Unauthorized
     */
    401: LoginResponse;
};

export type CoreApiLoginViewError = CoreApiLoginViewErrors[keyof CoreApiLoginViewErrors];

export type CoreApiLoginViewResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type CoreApiLoginViewResponse = CoreApiLoginViewResponses[keyof CoreApiLoginViewResponses];

export type CoreApiLogoutViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type CoreApiLogoutViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CoreApiChangePasswordViewData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Old Password
         */
        old_password: string;
        /**
         * New Password
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/set-password';
};

export type CoreApiChangePasswordViewErrors = {
    /**
     * Unauthorized
     */
    401: LoginResponse;
};

export type CoreApiChangePasswordViewError = CoreApiChangePasswordViewErrors[keyof CoreApiChangePasswordViewErrors];

export type CoreApiChangePasswordViewResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type CoreApiChangePasswordViewResponse = CoreApiChangePasswordViewResponses[keyof CoreApiChangePasswordViewResponses];

export type CoreApiAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/account';
};

export type CoreApiAccountResponses = {
    /**
     * OK
     */
    200: AccountResponse;
};

export type CoreApiAccountResponse = CoreApiAccountResponses[keyof CoreApiAccountResponses];

export type CoreApiUpdateProfileData = {
    /**
     * FormParams
     */
    body: {
        /**
         * First Name
         */
        first_name: string;
        /**
         * Last Name
         */
        last_name: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/profile';
};

export type CoreApiUpdateProfileResponses = {
    /**
     * OK
     */
    200: AccountResponse;
};

export type CoreApiUpdateProfileResponse = CoreApiUpdateProfileResponses[keyof CoreApiUpdateProfileResponses];

export type CoreApiPasswordResetRequestData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Email
         */
        email: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/password-reset-request';
};

export type CoreApiPasswordResetRequestResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CoreApiPasswordResetConfirmData = {
    /**
     * FormParams
     */
    body: {
        /**
         * Uid
         */
        uid: string;
        /**
         * Token
         */
        token: string;
        /**
         * New Password
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/password-reset-confirm';
};

export type CoreApiPasswordResetConfirmResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CoreApiSetLanguageData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Language
         */
        language: string;
    };
    url: '/api/set-language/';
};

export type CoreApiSetLanguageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MealsApiListCampsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/meals/camps';
};

export type MealsApiListCampsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<CampSchema>;
};

export type MealsApiListCampsResponse = MealsApiListCampsResponses[keyof MealsApiListCampsResponses];

export type MealsApiCreateCampData = {
    body: CampCreateSchema;
    path?: never;
    query?: never;
    url: '/api/meals/camps';
};

export type MealsApiCreateCampResponses = {
    /**
     * OK
     */
    200: CampSchema;
};

export type MealsApiCreateCampResponse = MealsApiCreateCampResponses[keyof MealsApiCreateCampResponses];

export type MealsApiDeleteCampData = {
    body?: never;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}';
};

export type MealsApiDeleteCampResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MealsApiGetCampData = {
    body?: never;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}';
};

export type MealsApiGetCampResponses = {
    /**
     * OK
     */
    200: CampSchema;
};

export type MealsApiGetCampResponse = MealsApiGetCampResponses[keyof MealsApiGetCampResponses];

export type MealsApiUpdateCampData = {
    body: CampUpdateSchema;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}';
};

export type MealsApiUpdateCampResponses = {
    /**
     * OK
     */
    200: CampSchema;
};

export type MealsApiUpdateCampResponse = MealsApiUpdateCampResponses[keyof MealsApiUpdateCampResponses];

export type MealsApiInviteCollaboratorData = {
    body: CollaboratorInviteSchema;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/collaborators';
};

export type MealsApiInviteCollaboratorResponses = {
    /**
     * OK
     */
    200: CampSchema;
};

export type MealsApiInviteCollaboratorResponse = MealsApiInviteCollaboratorResponses[keyof MealsApiInviteCollaboratorResponses];

export type MealsApiRemoveCollaboratorData = {
    body?: never;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/collaborators/{username}';
};

export type MealsApiRemoveCollaboratorResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MealsApiGetCurrentUserStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/meals/auth/me';
};

export type MealsApiGetCurrentUserStatusResponses = {
    /**
     * OK
     */
    200: CurrentUserStatusSchema;
};

export type MealsApiGetCurrentUserStatusResponse = MealsApiGetCurrentUserStatusResponses[keyof MealsApiGetCurrentUserStatusResponses];

export type MealsApiToggleCampMealDoneData = {
    body?: never;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
        /**
         * Meal Id
         */
        meal_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/meals/{meal_id}/toggle-done';
};

export type MealsApiToggleCampMealDoneResponses = {
    /**
     * OK
     */
    200: CampMealSchema;
};

export type MealsApiToggleCampMealDoneResponse = MealsApiToggleCampMealDoneResponses[keyof MealsApiToggleCampMealDoneResponses];

export type MealsApiGetInventoryStatusData = {
    body?: never;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/inventory-status';
};

export type MealsApiGetInventoryStatusResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<InventoryStatusSchema>;
};

export type MealsApiGetInventoryStatusResponse = MealsApiGetInventoryStatusResponses[keyof MealsApiGetInventoryStatusResponses];

export type MealsApiExportInventoryExcelData = {
    body?: never;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/inventory-status/export';
};

export type MealsApiExportInventoryExcelResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MealsApiListIngredientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
    };
    url: '/api/meals/ingredients';
};

export type MealsApiListIngredientsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<IngredientSchema>;
};

export type MealsApiListIngredientsResponse = MealsApiListIngredientsResponses[keyof MealsApiListIngredientsResponses];

export type MealsApiCreateIngredientData = {
    body: IngredientCreateSchema;
    path?: never;
    query?: never;
    url: '/api/meals/ingredients';
};

export type MealsApiCreateIngredientResponses = {
    /**
     * OK
     */
    200: IngredientSchema;
};

export type MealsApiCreateIngredientResponse = MealsApiCreateIngredientResponses[keyof MealsApiCreateIngredientResponses];

export type MealsApiListUnitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/meals/units';
};

export type MealsApiListUnitsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<string>;
};

export type MealsApiListUnitsResponse = MealsApiListUnitsResponses[keyof MealsApiListUnitsResponses];

export type MealsApiListTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/meals/tags';
};

export type MealsApiListTagsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<string>;
};

export type MealsApiListTagsResponse = MealsApiListTagsResponses[keyof MealsApiListTagsResponses];

export type MealsApiListRecipesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Tags
         */
        tags?: string | null;
        /**
         * Preference Id
         */
        preference_id?: number | null;
    };
    url: '/api/meals/recipes';
};

export type MealsApiListRecipesResponses = {
    /**
     * OK
     */
    200: RecipePaginatedSchema;
};

export type MealsApiListRecipesResponse = MealsApiListRecipesResponses[keyof MealsApiListRecipesResponses];

export type MealsApiCreateRecipeData = {
    body: RecipeCreateSchema;
    path?: never;
    query?: never;
    url: '/api/meals/recipes';
};

export type MealsApiCreateRecipeResponses = {
    /**
     * OK
     */
    200: RecipeSchema;
};

export type MealsApiCreateRecipeResponse = MealsApiCreateRecipeResponses[keyof MealsApiCreateRecipeResponses];

export type MealsApiImportRecipeData = {
    body: RecipeImportRequestSchema;
    path?: never;
    query?: never;
    url: '/api/meals/recipes/import';
};

export type MealsApiImportRecipeResponses = {
    /**
     * OK
     */
    200: RecipeSchema;
};

export type MealsApiImportRecipeResponse = MealsApiImportRecipeResponses[keyof MealsApiImportRecipeResponses];

export type MealsApiGetRecipeData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/meals/recipes/{recipe_id}';
};

export type MealsApiGetRecipeResponses = {
    /**
     * OK
     */
    200: RecipeSchema;
};

export type MealsApiGetRecipeResponse = MealsApiGetRecipeResponses[keyof MealsApiGetRecipeResponses];

export type MealsApiUpdateRecipeData = {
    body: RecipeUpdateSchema;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/meals/recipes/{recipe_id}';
};

export type MealsApiUpdateRecipeResponses = {
    /**
     * OK
     */
    200: RecipeSchema;
};

export type MealsApiUpdateRecipeResponse = MealsApiUpdateRecipeResponses[keyof MealsApiUpdateRecipeResponses];

export type MealsApiListRecipeIngredientsData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/meals/recipes/{recipe_id}/ingredients';
};

export type MealsApiListRecipeIngredientsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<RecipeIngredientSchema>;
};

export type MealsApiListRecipeIngredientsResponse = MealsApiListRecipeIngredientsResponses[keyof MealsApiListRecipeIngredientsResponses];

export type MealsApiAddRecipeIngredientData = {
    body: RecipeIngredientCreateOrMapSchema;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/meals/recipes/{recipe_id}/ingredients';
};

export type MealsApiAddRecipeIngredientResponses = {
    /**
     * OK
     */
    200: RecipeIngredientSchema;
};

export type MealsApiAddRecipeIngredientResponse = MealsApiAddRecipeIngredientResponses[keyof MealsApiAddRecipeIngredientResponses];

export type MealsApiDeleteRecipeIngredientData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
        /**
         * Ingredient Id
         */
        ingredient_id: string;
    };
    query?: never;
    url: '/api/meals/recipes/{recipe_id}/ingredients/{ingredient_id}';
};

export type MealsApiDeleteRecipeIngredientResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MealsApiUpdateRecipeIngredientData = {
    body: RecipeIngredientUpdateSchema;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
        /**
         * Ingredient Id
         */
        ingredient_id: string;
    };
    query?: never;
    url: '/api/meals/recipes/{recipe_id}/ingredients/{ingredient_id}';
};

export type MealsApiUpdateRecipeIngredientResponses = {
    /**
     * OK
     */
    200: RecipeIngredientSchema;
};

export type MealsApiUpdateRecipeIngredientResponse = MealsApiUpdateRecipeIngredientResponses[keyof MealsApiUpdateRecipeIngredientResponses];

export type MealsApiInviteRecipeCollaboratorData = {
    body: CollaboratorInviteSchema;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
    };
    query?: never;
    url: '/api/meals/recipes/{recipe_id}/collaborators';
};

export type MealsApiInviteRecipeCollaboratorResponses = {
    /**
     * OK
     */
    200: RecipeSchema;
};

export type MealsApiInviteRecipeCollaboratorResponse = MealsApiInviteRecipeCollaboratorResponses[keyof MealsApiInviteRecipeCollaboratorResponses];

export type MealsApiRemoveRecipeCollaboratorData = {
    body?: never;
    path: {
        /**
         * Recipe Id
         */
        recipe_id: string;
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/meals/recipes/{recipe_id}/collaborators/{username}';
};

export type MealsApiRemoveRecipeCollaboratorResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MealsApiListPreferencesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/meals/preferences';
};

export type MealsApiListPreferencesResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<DietaryPreferenceSchema>;
};

export type MealsApiListPreferencesResponse = MealsApiListPreferencesResponses[keyof MealsApiListPreferencesResponses];

export type MealsApiListCampMealsData = {
    body?: never;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/meals';
};

export type MealsApiListCampMealsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<CampMealSchema>;
};

export type MealsApiListCampMealsResponse = MealsApiListCampMealsResponses[keyof MealsApiListCampMealsResponses];

export type MealsApiCreateCampMealData = {
    body: CampMealCreateSchema;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/meals';
};

export type MealsApiCreateCampMealResponses = {
    /**
     * OK
     */
    200: CampMealSchema;
};

export type MealsApiCreateCampMealResponse = MealsApiCreateCampMealResponses[keyof MealsApiCreateCampMealResponses];

export type MealsApiDeleteCampMealData = {
    body?: never;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
        /**
         * Meal Id
         */
        meal_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/meals/{meal_id}';
};

export type MealsApiDeleteCampMealResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MealsApiUpdateCampMealData = {
    body: CampMealUpdateSchema;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
        /**
         * Meal Id
         */
        meal_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/meals/{meal_id}';
};

export type MealsApiUpdateCampMealResponses = {
    /**
     * OK
     */
    200: CampMealSchema;
};

export type MealsApiUpdateCampMealResponse = MealsApiUpdateCampMealResponses[keyof MealsApiUpdateCampMealResponses];

export type MealsApiListCampGeneralItemsData = {
    body?: never;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/general-items';
};

export type MealsApiListCampGeneralItemsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<GeneralCampItemSchema>;
};

export type MealsApiListCampGeneralItemsResponse = MealsApiListCampGeneralItemsResponses[keyof MealsApiListCampGeneralItemsResponses];

export type MealsApiCreateCampGeneralItemData = {
    body: GeneralCampItemCreateSchema;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/general-items';
};

export type MealsApiCreateCampGeneralItemResponses = {
    /**
     * OK
     */
    200: GeneralCampItemSchema;
};

export type MealsApiCreateCampGeneralItemResponse = MealsApiCreateCampGeneralItemResponses[keyof MealsApiCreateCampGeneralItemResponses];

export type MealsApiDeleteCampGeneralItemData = {
    body?: never;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/general-items/{item_id}';
};

export type MealsApiDeleteCampGeneralItemResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MealsApiAddManualShoppingItemData = {
    body: ShoppingListManualItemSchema;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/shopping-lists/add-manual-item';
};

export type MealsApiAddManualShoppingItemResponses = {
    /**
     * OK
     */
    200: ShoppingListItemSchema;
};

export type MealsApiAddManualShoppingItemResponse = MealsApiAddManualShoppingItemResponses[keyof MealsApiAddManualShoppingItemResponses];

export type MealsApiGenerateShoppingListData = {
    body: ShoppingListGenerateRequestSchema;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/shopping-list/generate';
};

export type MealsApiGenerateShoppingListResponses = {
    /**
     * OK
     */
    200: ShoppingListSchema;
};

export type MealsApiGenerateShoppingListResponse = MealsApiGenerateShoppingListResponses[keyof MealsApiGenerateShoppingListResponses];

export type MealsApiMoveGeneralItemsToShoppingListData = {
    body?: never;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
        /**
         * List Id
         */
        list_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/shopping-lists/{list_id}/move-general-items';
};

export type MealsApiMoveGeneralItemsToShoppingListResponses = {
    /**
     * OK
     */
    200: ShoppingListSchema;
};

export type MealsApiMoveGeneralItemsToShoppingListResponse = MealsApiMoveGeneralItemsToShoppingListResponses[keyof MealsApiMoveGeneralItemsToShoppingListResponses];

export type MealsApiDeleteShoppingListData = {
    body?: never;
    path: {
        /**
         * List Id
         */
        list_id: string;
    };
    query?: never;
    url: '/api/meals/shopping-lists/{list_id}';
};

export type MealsApiDeleteShoppingListResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MealsApiGetShoppingListData = {
    body?: never;
    path: {
        /**
         * List Id
         */
        list_id: string;
    };
    query?: never;
    url: '/api/meals/shopping-lists/{list_id}';
};

export type MealsApiGetShoppingListResponses = {
    /**
     * OK
     */
    200: ShoppingListSchema;
};

export type MealsApiGetShoppingListResponse = MealsApiGetShoppingListResponses[keyof MealsApiGetShoppingListResponses];

export type MealsApiExportShoppingListData = {
    body?: never;
    path: {
        /**
         * List Id
         */
        list_id: string;
    };
    query?: never;
    url: '/api/meals/shopping-lists/{list_id}/export';
};

export type MealsApiExportShoppingListResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MealsApiListCampShoppingListsData = {
    body?: never;
    path: {
        /**
         * Camp Id
         */
        camp_id: string;
    };
    query?: never;
    url: '/api/meals/camps/{camp_id}/shopping-lists';
};

export type MealsApiListCampShoppingListsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<ShoppingListOverviewSchema>;
};

export type MealsApiListCampShoppingListsResponse = MealsApiListCampShoppingListsResponses[keyof MealsApiListCampShoppingListsResponses];

export type MealsApiGetSharedShoppingListData = {
    body?: never;
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/api/meals/shared/shopping-lists/{token}';
};

export type MealsApiGetSharedShoppingListResponses = {
    /**
     * OK
     */
    200: ShoppingListSchema;
};

export type MealsApiGetSharedShoppingListResponse = MealsApiGetSharedShoppingListResponses[keyof MealsApiGetSharedShoppingListResponses];

export type MealsApiExportSharedShoppingListData = {
    body?: never;
    path: {
        /**
         * Token
         */
        token: string;
    };
    query?: never;
    url: '/api/meals/shared/shopping-lists/{token}/export';
};

export type MealsApiExportSharedShoppingListResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MealsApiToggleSharedShoppingItemData = {
    body?: never;
    path: {
        /**
         * Token
         */
        token: string;
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/meals/shared/shopping-lists/{token}/items/{item_id}/toggle';
};

export type MealsApiToggleSharedShoppingItemResponses = {
    /**
     * OK
     */
    200: ShoppingListItemSchema;
};

export type MealsApiToggleSharedShoppingItemResponse = MealsApiToggleSharedShoppingItemResponses[keyof MealsApiToggleSharedShoppingItemResponses];

export type ContentApiGetTextsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Lang
         */
        lang?: string;
    };
    url: '/api/content/texts/';
};

export type ContentApiGetTextsResponses = {
    /**
     * OK
     */
    200: unknown;
};
