// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { MealsApiCreateCampData, MealsApiCreateCampGeneralItemData, MealsApiCreateCampGeneralItemResponses, MealsApiCreateCampResponses, MealsApiCreateIngredientData, MealsApiCreateIngredientResponses, MealsApiCreateRecipeData, MealsApiCreateRecipeResponses, MealsApiGenerateShoppingListData, MealsApiGenerateShoppingListResponses, MealsApiGetCampData, MealsApiGetCampResponses, MealsApiListCampGeneralItemsData, MealsApiListCampGeneralItemsResponses, MealsApiListCampsData, MealsApiListCampsResponses, MealsApiListIngredientsData, MealsApiListIngredientsResponses, MealsApiListRecipesData, MealsApiListRecipesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Camps
 */
export const mealsApiListCamps = <ThrowOnError extends boolean = false>(options?: Options<MealsApiListCampsData, ThrowOnError>) => (options?.client ?? client).get<MealsApiListCampsResponses, unknown, ThrowOnError>({ url: '/api/camps', ...options });

/**
 * Create Camp
 */
export const mealsApiCreateCamp = <ThrowOnError extends boolean = false>(options: Options<MealsApiCreateCampData, ThrowOnError>) => (options.client ?? client).post<MealsApiCreateCampResponses, unknown, ThrowOnError>({
    url: '/api/camps',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Camp
 */
export const mealsApiGetCamp = <ThrowOnError extends boolean = false>(options: Options<MealsApiGetCampData, ThrowOnError>) => (options.client ?? client).get<MealsApiGetCampResponses, unknown, ThrowOnError>({ url: '/api/camps/{camp_id}', ...options });

/**
 * List Ingredients
 */
export const mealsApiListIngredients = <ThrowOnError extends boolean = false>(options?: Options<MealsApiListIngredientsData, ThrowOnError>) => (options?.client ?? client).get<MealsApiListIngredientsResponses, unknown, ThrowOnError>({ url: '/api/ingredients', ...options });

/**
 * Create Ingredient
 */
export const mealsApiCreateIngredient = <ThrowOnError extends boolean = false>(options: Options<MealsApiCreateIngredientData, ThrowOnError>) => (options.client ?? client).post<MealsApiCreateIngredientResponses, unknown, ThrowOnError>({
    url: '/api/ingredients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Recipes
 */
export const mealsApiListRecipes = <ThrowOnError extends boolean = false>(options?: Options<MealsApiListRecipesData, ThrowOnError>) => (options?.client ?? client).get<MealsApiListRecipesResponses, unknown, ThrowOnError>({ url: '/api/recipes', ...options });

/**
 * Create Recipe
 */
export const mealsApiCreateRecipe = <ThrowOnError extends boolean = false>(options: Options<MealsApiCreateRecipeData, ThrowOnError>) => (options.client ?? client).post<MealsApiCreateRecipeResponses, unknown, ThrowOnError>({
    url: '/api/recipes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Camp General Items
 */
export const mealsApiListCampGeneralItems = <ThrowOnError extends boolean = false>(options: Options<MealsApiListCampGeneralItemsData, ThrowOnError>) => (options.client ?? client).get<MealsApiListCampGeneralItemsResponses, unknown, ThrowOnError>({ url: '/api/camps/{camp_id}/general-items', ...options });

/**
 * Create Camp General Item
 */
export const mealsApiCreateCampGeneralItem = <ThrowOnError extends boolean = false>(options: Options<MealsApiCreateCampGeneralItemData, ThrowOnError>) => (options.client ?? client).post<MealsApiCreateCampGeneralItemResponses, unknown, ThrowOnError>({
    url: '/api/camps/{camp_id}/general-items',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate Shopping List
 */
export const mealsApiGenerateShoppingList = <ThrowOnError extends boolean = false>(options: Options<MealsApiGenerateShoppingListData, ThrowOnError>) => (options.client ?? client).post<MealsApiGenerateShoppingListResponses, unknown, ThrowOnError>({ url: '/api/camps/{camp_id}/shopping-list/generate', ...options });
