// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

/**
 * CampSchema
 */
export type CampSchema = {
  /**
   * Id
   */
  id?: string | null;
  /**
   * Name
   */
  name: string;
  /**
   * Default People Count
   */
  default_people_count?: number;
  /**
   * Start Date
   */
  start_date: string;
  /**
   * End Date
   */
  end_date: string;
  /**
   * Owner
   */
  owner: number;
};

/**
 * CampCreateSchema
 */
export type CampCreateSchema = {
  /**
   * Name
   */
  name: string;
  /**
   * Default People Count
   */
  default_people_count?: number;
  /**
   * Start Date
   */
  start_date: string;
  /**
   * End Date
   */
  end_date: string;
};

/**
 * IngredientSchema
 */
export type IngredientSchema = {
  /**
   * Id
   */
  id?: string | null;
  /**
   * Name
   */
  name: string;
  /**
   * Category
   */
  category?: string;
  /**
   * Base Unit
   *
   * e.g. grams, pieces, ml
   */
  base_unit: string;
};

/**
 * IngredientCreateSchema
 */
export type IngredientCreateSchema = {
  /**
   * Name
   */
  name: string;
  /**
   * Category
   */
  category?: string;
  /**
   * Base Unit
   *
   * e.g. grams, pieces, ml
   */
  base_unit: string;
};

/**
 * RecipeSchema
 */
export type RecipeSchema = {
  /**
   * Id
   */
  id?: string | null;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Instructions
   */
  instructions?: string | null;
  /**
   * Owner
   */
  owner?: number | null;
  /**
   * Tags
   *
   * List of dietary tags like Vegan, Gluten-Free
   */
  tags?: {
    [key: string]: unknown;
  } | null;
  /**
   * Default Portions
   *
   * How many people this recipe serves as written
   */
  default_portions?: number;
};

/**
 * RecipeCreateSchema
 */
export type RecipeCreateSchema = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Instructions
   */
  instructions?: string | null;
  /**
   * Tags
   *
   * List of dietary tags like Vegan, Gluten-Free
   */
  tags?: {
    [key: string]: unknown;
  } | null;
  /**
   * Default Portions
   *
   * How many people this recipe serves as written
   */
  default_portions?: number;
};

/**
 * GeneralCampItemSchema
 */
export type GeneralCampItemSchema = {
  /**
   * ID
   */
  id?: number | null;
  /**
   * Camp
   */
  camp: string;
  /**
   * Name
   */
  name: string;
  /**
   * Amount
   */
  amount: string;
  /**
   * Category
   */
  category?: string;
};

/**
 * GeneralCampItemCreateSchema
 */
export type GeneralCampItemCreateSchema = {
  /**
   * Name
   */
  name: string;
  /**
   * Amount
   */
  amount: string;
  /**
   * Category
   */
  category?: string;
};

/**
 * ShoppingListItemSchema
 */
export type ShoppingListItemSchema = {
  /**
   * ID
   */
  id?: number | null;
  /**
   * Shopping List
   */
  shopping_list: string;
  /**
   * Ingredient
   */
  ingredient?: string | null;
  /**
   * Custom Name
   */
  custom_name?: string | null;
  /**
   * Amount
   */
  amount: number;
  /**
   * Unit
   */
  unit: string;
  /**
   * Category
   */
  category: string;
  /**
   * Is Checked
   */
  is_checked?: boolean;
};

/**
 * ShoppingListSchema
 */
export type ShoppingListSchema = {
  /**
   * Id
   */
  id: string;
  /**
   * Camp Id
   */
  camp_id: string;
  /**
   * Shared Token
   */
  shared_token: string;
  /**
   * Items
   */
  items: Array<ShoppingListItemSchema>;
};

export type MealsApiListCampsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/camps";
};

export type MealsApiListCampsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<CampSchema>;
};

export type MealsApiListCampsResponse =
  MealsApiListCampsResponses[keyof MealsApiListCampsResponses];

export type MealsApiCreateCampData = {
  body: CampCreateSchema;
  path?: never;
  query?: never;
  url: "/api/camps";
};

export type MealsApiCreateCampResponses = {
  /**
   * OK
   */
  200: CampSchema;
};

export type MealsApiCreateCampResponse =
  MealsApiCreateCampResponses[keyof MealsApiCreateCampResponses];

export type MealsApiGetCampData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/camps/{camp_id}";
};

export type MealsApiGetCampResponses = {
  /**
   * OK
   */
  200: CampSchema;
};

export type MealsApiGetCampResponse =
  MealsApiGetCampResponses[keyof MealsApiGetCampResponses];

export type MealsApiListIngredientsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Q
     */
    q?: string | null;
  };
  url: "/api/ingredients";
};

export type MealsApiListIngredientsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<IngredientSchema>;
};

export type MealsApiListIngredientsResponse =
  MealsApiListIngredientsResponses[keyof MealsApiListIngredientsResponses];

export type MealsApiCreateIngredientData = {
  body: IngredientCreateSchema;
  path?: never;
  query?: never;
  url: "/api/ingredients";
};

export type MealsApiCreateIngredientResponses = {
  /**
   * OK
   */
  200: IngredientSchema;
};

export type MealsApiCreateIngredientResponse =
  MealsApiCreateIngredientResponses[keyof MealsApiCreateIngredientResponses];

export type MealsApiListRecipesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Q
     */
    q?: string | null;
  };
  url: "/api/recipes";
};

export type MealsApiListRecipesResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<RecipeSchema>;
};

export type MealsApiListRecipesResponse =
  MealsApiListRecipesResponses[keyof MealsApiListRecipesResponses];

export type MealsApiCreateRecipeData = {
  body: RecipeCreateSchema;
  path?: never;
  query?: never;
  url: "/api/recipes";
};

export type MealsApiCreateRecipeResponses = {
  /**
   * OK
   */
  200: RecipeSchema;
};

export type MealsApiCreateRecipeResponse =
  MealsApiCreateRecipeResponses[keyof MealsApiCreateRecipeResponses];

export type MealsApiListCampGeneralItemsData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/camps/{camp_id}/general-items";
};

export type MealsApiListCampGeneralItemsResponses = {
  /**
   * Response
   *
   * OK
   */
  200: Array<GeneralCampItemSchema>;
};

export type MealsApiListCampGeneralItemsResponse =
  MealsApiListCampGeneralItemsResponses[keyof MealsApiListCampGeneralItemsResponses];

export type MealsApiCreateCampGeneralItemData = {
  body: GeneralCampItemCreateSchema;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/camps/{camp_id}/general-items";
};

export type MealsApiCreateCampGeneralItemResponses = {
  /**
   * OK
   */
  200: GeneralCampItemSchema;
};

export type MealsApiCreateCampGeneralItemResponse =
  MealsApiCreateCampGeneralItemResponses[keyof MealsApiCreateCampGeneralItemResponses];

export type MealsApiGenerateShoppingListData = {
  body?: never;
  path: {
    /**
     * Camp Id
     */
    camp_id: string;
  };
  query?: never;
  url: "/api/camps/{camp_id}/shopping-list/generate";
};

export type MealsApiGenerateShoppingListResponses = {
  /**
   * OK
   */
  200: ShoppingListSchema;
};

export type MealsApiGenerateShoppingListResponse =
  MealsApiGenerateShoppingListResponses[keyof MealsApiGenerateShoppingListResponses];
