# Generated by Django 6.0.3 on 2026-04-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UIText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique key like 'nav.camps', 'btn.save'",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("text", models.TextField(help_text="The UI text content")),
                (
                    "text_de",
                    models.TextField(help_text="The UI text content", null=True),
                ),
                (
                    "text_fr",
                    models.TextField(help_text="The UI text content", null=True),
                ),
            ],
            options={
                "verbose_name": "UI Text",
                "verbose_name_plural": "UI Texts",
                "ordering": ["key"],
            },
        ),
    ]
